services:
  app:
    container_name: hawler-forcast-backend-${APP_ENV}
    build:
      context: .
      dockerfile: Dockerfile
      target: php
      args:
        - APP_ENV=${APP_ENV}
    env_file:
      - .env
    environment:
      - CONTAINER_ROLE=app
      - APP_ENV=${APP_ENV}
    working_dir: /var/www
    volumes:
      - storage-data:/var/www/storage/app
      - logs-data:/var/www/storage/logs
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - traefik.enable=true

  horizon:
    container_name: hawler-forcast-backend-horizon-${APP_ENV}
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    env_file:
      - .env
    environment:
      - CONTAINER_ROLE=horizon
    working_dir: /var/www
    volumes:
      - storage-data:/var/www/storage/app
      - logs-data:/var/www/storage/logs
    depends_on:
      - app
    networks:
      - dokploy-network
    restart: unless-stopped

  scheduler:
    container_name: hawler-forcast-backend-scheduler-${APP_ENV}
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    env_file:
      - .env
    environment:
      - CONTAINER_ROLE=scheduler
    working_dir: /var/www
    volumes:
      - storage-data:/var/www/storage/app
      - logs-data:/var/www/storage/logs
    depends_on:
      - app
    networks:
      - dokploy-network
    restart: unless-stopped

volumes:
  storage-data:
  logs-data:

networks:
  dokploy-network:
    external: true
